[FFMPEG]
CopyUnprocessed = false
MimicMode = false
HideErrors = false
WebpRGBA = true

[AUDIO]
Extension = "opus"
BitRate = "320k"

[IMAGE]
Extension = "avif"
Quality = 20

[VIDEO]
Extension = "webm"
Codec = "libvpx-vp9"