[FFMPEG]
FFmpegParams = "-n -hide_banner -loglevel error"
MimicMode = false

[AUDIO]
Extension = "mp3"
BitRate = "320k"

[IMAGE]
Extension = "png"
CompLevel = 20
JpegComp = 3

[VIDEO]
Extension = "mp4"
Codec = "libvpx-vp9"
