[FFMPEG]
FFmpegParams = "-n -hide_banner -loglevel quiet -hwaccel auto"
CopyUnprocessed = false
MimicMode = false
HideErrors = false
WebpRGBA = true

[AUDIO]
Extension = "mp3"
BitRate = "320k"

[IMAGE]
Extension = "jpg"
CompLevel = 20

[VIDEO]
Extension = "mp4"
Codec = "libvpx-vp9"