[FFMPEG]
FFmpegParams = "-n -hide_banner -loglevel quiet"
CopyUnprocessed = false
MimicMode = false
HideErrors = false

[AUDIO]
Extension = "mp3"
BitRate = "320k"

[IMAGE]
Extension = "jpg"
CompLevel = 20
JpegComp = 3

[VIDEO]
Extension = "mp4"
Codec = "libvpx-vp9"
