[FFMPEG]
FFmpegParams = "-hide_banner -loglevel error"
MimicMode = true

[AUDIO]
Extension = "mp3"
BitRate = "320k"

[IMAGE]
Extension = "png"
CompLevel = 20
JpegComp = 3

[VIDEO]
Extension = "mp4"
Codec = "libvpx-vp9"
