[FFMPEG]
CopyUnprocessed = true
ForceCompress = false
MimicMode = true
HideErrors = true
WebpRGBA = true

[AUDIO]
Extension = "opus"
BitRate = "128k"

[IMAGE]
Extension = "avif"
FallBackExtension = "webp"
Lossless = false
Quality = 80

[VIDEO]
Extension = "webm"
Codec = "libvpx-vp9"