[FFMPEG]
CopyUnprocessed = false
MimicMode = false
HideErrors = false
WebpRGBA = true

[AUDIO]
Extension = "opus"
BitRate = "320k"

[IMAGE]
Extension = "avif"
FallBackExtension = "webp"
Lossless = false
Quality = 80

[VIDEO]
Extension = "webm"
Codec = "libvpx-vp9"