[FFMPEG]
FFmpegParams = "-hide_banner -loglevel error"

[AUDIO]
Extension = "mp3"
BitRate = "320k"

[IMAGE]
Extension = "jpg"
CompLevel = 100
JpegComp = 3

[VIDEO]
Extension = "webm"
Codec = "libvpx-vp9"
