[FFMPEG]
FFmpegParams = "-hide_banner -loglevel error"

[AUDIO]
Extension = "original"
BitRate = "320k"

[IMAGE]
Extension = "original"
CompLevel = 20
JpegComp = 3

[VIDEO]
Extension = "original"
Codec = "libvpx-vp9"
